name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  test:
    name: Test
    uses: ./.github/workflows/test.yml

  typecheck:
    name: Typecheck
    uses: ./.github/workflows/typecheck.yml

  build-assets:
    name: Build Assets
    uses: ./.github/workflows/build-assets.yml
