name: Push to DigitalOcean

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'README.md'

jobs:
  deploy:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Build web image
        run: docker build -t registry.digitalocean.com/stats-go/web:latest .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push web image
        run: docker push registry.digitalocean.com/stats-go/web:latest
