name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: '0 9 * 1,8-12 *'

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  deploy:
    name: Build and push
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 900

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: "registry.digitalocean.com/stats-go/web:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            "database_url=${{ secrets.DATABASE_URL }}"
